version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        PUID: ${UID}
        PHP_VERSION: ${PHP_VERSION}
      target: dev
    container_name: task-scheduler-application
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - '4200:80'
    depends_on:
      - database
    links:
      - database
    networks:
      - task-scheduler

  database:
    image: mysql:8
    container_name: task-scheduler-database
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - task-scheduler-data:/var/lib/mysql
    networks:
      - task-scheduler

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: task-scheduler-admin
    depends_on:
      - database
    environment:
      PMA_HOST: database
    ports:
      - '4300:80'
    links:
      - database
    networks:
      - task-scheduler

networks:
  task-scheduler:

volumes:
  task-scheduler-data:
